# Generated by Django 5.0 on 2023-12-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_meeting_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('one_time', 'One Time Only')], default='one_time', max_length=50),
        ),
    ]
